# Quickstart artifakt.yml
title: Kubernetes GCP Cluster
description: Kubernetes Cluster on GCP with terraform
cloud_provider: gcp
build_engine: terraform
available_regions:
  - northamerica-northeast1
  - us-central1
  - us-east1
  - us-east4
  - us-west1
  - southamerica-east1
  - europe-west1
  - europe-west2
  - europe-west3
  - europe-west4
  - asia-east1
  - asia-northeast1
  - asia-south1
  - asia-southeast1
  - australia-southeast1
image: https://assets.artifakt.io/kubernetes.png
category: other
main_language: other
licence:
   code: mit
   name: MIT
tags:
 - gcp
 - Kubernetes
 - Docker
infrastructure:
  diagram: https://assets.artifakt.io/kubernetes-gcp-terraform.png
  build_time: 300  #in seconds 
  cost_estimation:
    monthly_price: 72.82 #in dollars per month 
    details: calculated for 3 nodes n1-standard-1 in us-central-1
output:
 -
  code: endpoint
  name: Endpoint
  description: public ip endpoint to reach kubernetes
  category: text
 -
  code: instance_group_urls
  name: Instance Group Urls
  description: Urls for all instance grousp ( 1 per az)
  category: url
 -
  code: password
  name: Password
  description: Autogenerated master password to access kubernetes
  category: text
 -
  code: username
  name: Username
  description: Autogenerated master username to access kubernetes
  category: text